/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cycling-jersey.drc.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.M740158_mesh_zipper.geometry} material={materials.blinn9} scale={100} />
      <mesh geometry={nodes.M740158_mesh_band.geometry} material={materials.blinn8} scale={100} />
      <mesh geometry={nodes.M740158_mesh_out.geometry} material={materials.blinn10} scale={100} />
      <mesh geometry={nodes.M740158_mesh_in.geometry} material={materials.blinn2} scale={100} />
      <mesh geometry={nodes.M740158_mesh_zipp.geometry} material={materials.blinn4} scale={100} />
    </group>
  )
}

useGLTF.preload('/cycling-jersey.drc.glb')
